import { useEffect, useMemo, useState } from "react";
import { createUiClient, type UiResult, type UiViewEnvelope } from "../api.ts";
import { ViewFrame } from "../components/ViewFrame.tsx";

interface ActionControl{readonly action_class_ref?:unknown;readonly availability_result_ref?:unknown;readonly withholding_reason_ref?:unknown;readonly actor_ref?:unknown;readonly role_assignment_ref?:unknown;readonly role_ref?:unknown;readonly holder_ref?:unknown;}
function routeParts():{ticketId?:string;actionClass?:string}{const match=/^\/tickets\/([^/]+)\/action\/([^/]+)/.exec(location.pathname);if(!match)return{};try{return{ticketId:decodeURIComponent(match[1]!),actionClass:decodeURIComponent(match[2]!)}}catch{return{}};}
function text(value:unknown):string|undefined{return typeof value==="string"&&value.length>0?value:undefined;}
function number(value:unknown):number|undefined{return typeof value==="number"&&Number.isSafeInteger(value)&&value>=0?value:undefined;}
function controls(value:unknown):readonly ActionControl[]{return Array.isArray(value)?value.filter((item):item is ActionControl=>!!item&&typeof item==="object"):[];}
export function GuidedActionView(){
  const route=useMemo(routeParts,[]);const[projection,setProjection]=useState<UiViewEnvelope>();const[result,setResult]=useState<UiResult>();const[failure,setFailure]=useState<string>();const[busy,setBusy]=useState(false);
  useEffect(()=>{if(!route.ticketId){setFailure("TICKET_ID_MISSING");return;}const client=createUiClient();void client.read(`/tickets/${encodeURIComponent(route.ticketId)}`).then(setProjection).catch((error:unknown)=>setFailure(error instanceof Error?error.message:"GUIDED_ACTION_PROJECTION_UNAVAILABLE"));},[route.ticketId]);
  const data=projection?.data;const aggregateVersion=number(data?.["aggregate_version"]);const contract=text(data?.["action_contract_ref"]);const control=controls(data?.["action_controls"]).find((item)=>text(item.action_class_ref)===route.actionClass);const available=text(control?.availability_result_ref)==="AVAILABLE";const actorRef=text(control?.actor_ref);const assignmentRef=text(control?.role_assignment_ref);const roleRef=text(control?.role_ref);const symbolicHolder=text(control?.holder_ref);const current=projection?.currentness_ref==="CURRENT";
  async function submit():Promise<void>{if(!route.ticketId||!route.actionClass||!projection||!contract||aggregateVersion===undefined||!actorRef||!assignmentRef||!available||!current)return;setBusy(true);setFailure(undefined);try{const client=createUiClient();const intentTime=new Date().toISOString();const outcome=await client.intent({intent_contract_ref:contract,subject_ref:route.ticketId,correlation_id:crypto.randomUUID(),presented_source_version_ref:projection.source_version_set_ref,expected_aggregate_version:aggregateVersion,payload:{action_intent_id:crypto.randomUUID(),ticket_id:route.ticketId,actor_ref:actorRef,role_assignment_ref:assignmentRef,requested_action_class:route.actionClass,presented_source_version_ref:projection.source_version_set_ref,expected_aggregate_version:aggregateVersion,intent_time:intentTime}});setResult(outcome);const refreshed=await client.read(`/tickets/${encodeURIComponent(route.ticketId)}`);setProjection(refreshed);}catch(error){setFailure(error instanceof Error?error.message:"GUIDED_ACTION_FAILED");}finally{setBusy(false);}}
  return <ViewFrame viewId="UX-RS-04" title="Guided Action"><p>Review current actor, target, evidence, currentness and expected version before confirmation. Submission becomes authoritative only after server revalidation, durable result, and refetch.</p>{failure?<p role="alert">{failure}</p>:null}<section data-action-class={route.actionClass??"UNKNOWN"}><p><strong>Ticket:</strong> {route.ticketId??"Missing"}</p><p><strong>Action:</strong> {route.actionClass??"Missing"}</p><p><strong>Current Role:</strong> {roleRef??"Not currently bound"}</p><p><strong>Bound Holder:</strong> {symbolicHolder??"Not currently bound"}</p><p><strong>Expected aggregate version:</strong> {aggregateVersion??"Unknown"}</p><p><strong>Currentness:</strong> {projection?.currentness_ref??"Unknown"}</p><p><strong>Availability:</strong> {available?"AVAILABLE":text(control?.withholding_reason_ref)??"WITHHELD / NOT PRESENTED"}</p>{available&&current&&actorRef&&assignmentRef?<button type="button" disabled={busy} onClick={()=>void submit()}>{busy?"Submitting…":"Confirm governed action"}</button>:<p>Action is fail-closed until the current server projection authorizes it.</p>}{result?<p role="status" data-action-result={result.result}>Authoritative result: {result.result}; durable={String(result.durable)}</p>:null}{route.ticketId?<p><a href={`/tickets/${encodeURIComponent(route.ticketId)}`}>Return to Ticket Console</a></p>:null}</section></ViewFrame>;
}
