import { useEffect, useMemo, useState } from "react";
import { createUiClient, deriveActionPresentation, type UiResult, type UiViewEnvelope } from "../api.ts";
import { CurrentnessBanner, type Currentness } from "../components/CurrentnessBanner.tsx";
import { ViewFrame } from "../components/ViewFrame.tsx";

const currentnessValues=new Set<Currentness>(["CURRENT","STALE","CONTRADICTORY","MIXED_SOURCE","MISSING_BINDING","UNCERTAIN"]);
function currentness(value:unknown):Currentness{return typeof value==="string"&&currentnessValues.has(value as Currentness)?value as Currentness:"MISSING_BINDING";}
function text(value:unknown):string|undefined{return typeof value==="string"&&value.length>0?value:undefined;}
function number(value:unknown):number|undefined{return typeof value==="number"&&Number.isSafeInteger(value)&&value>=0?value:undefined;}
function stringArray(value:unknown):readonly string[]{return Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"&&item.length>0):[];}
function bool(value:unknown):boolean{return value===true;}
function currentTicketId():string|undefined{const match=/^\/tickets\/([^/]+)/.exec(location.pathname);if(!match?.[1])return undefined;try{return decodeURIComponent(match[1]);}catch{return undefined;}}

export function TicketConsoleView({mode="console"}:{mode?:"console"|"closed"|"history"}){
  if(mode!=="console")return <ViewFrame viewId={mode==="closed"?"UX-RS-12":"UX-RS-HISTORY"} title={mode==="closed"?"Closed Ticket / Correction / Successor":"Ticket Audit / History"}/>;
  const ticketId=useMemo(currentTicketId,[]);const[projection,setProjection]=useState<UiViewEnvelope>();const[failure,setFailure]=useState<string>();const[actionResult,setActionResult]=useState<UiResult>();const[busy,setBusy]=useState(false);
  useEffect(()=>{if(!ticketId){setFailure("TICKET_ID_MISSING");return;}const client=createUiClient();void client.read(`/tickets/${encodeURIComponent(ticketId)}`).then((result)=>{if(result.view_id!=="UX-RS-03")throw new Error("TICKET_CONSOLE_PROJECTION_VIEW_MISMATCH");setProjection(result);}).catch((error:unknown)=>setFailure(error instanceof Error?error.message:"TICKET_CONSOLE_PROJECTION_UNAVAILABLE"));},[ticketId]);
  const data=projection?.data;const state=text(data?.["current_state_code"]);const aggregateVersion=number(data?.["aggregate_version"]);const holderRef=text(data?.["holder_ref"])??text(data?.["current_responsible_holder_ref"]);const roleAssignmentRef=text(data?.["role_assignment_ref"])??text(data?.["action_authority_assignment_ref"]);const authorityResultRef=text(data?.["authority_result_ref"]);const gateResultRef=text(data?.["gate_result_ref"]);const actionContractRef=text(data?.["action_contract_ref"]);const availableActions=stringArray(data?.["available_actions"]);const restrictionProfile=text(data?.["restriction_profile_ref"]);const day2Stage=text(data?.["day2_stage"]);const trainerAvailable=bool(data?.["day2_trainer_available"]);const projectionCurrentness=currentness(projection?.currentness_ref);
  const activatePresentation=deriveActionPresentation({present:availableActions.includes("ACTIVATE"),permitted:availableActions.includes("ACTIVATE"),currentness:projectionCurrentness,missingBinding:!holderRef||!roleAssignmentRef||!authorityResultRef||!gateResultRef||aggregateVersion===undefined,reason:restrictionProfile??"ROLE_AUTHORITY_GATE_BINDING_REQUIRED"});
  async function activate():Promise<void>{if(!ticketId||!projection||!holderRef||!roleAssignmentRef||!actionContractRef||aggregateVersion===undefined)return;setBusy(true);setFailure(undefined);try{const client=createUiClient();const intentTime=new Date().toISOString();const result=await client.intent({intent_contract_ref:actionContractRef,subject_ref:ticketId,correlation_id:crypto.randomUUID(),presented_source_version_ref:projection.source_version_set_ref,expected_aggregate_version:aggregateVersion,payload:{action_intent_id:crypto.randomUUID(),ticket_id:ticketId,actor_ref:holderRef,role_assignment_ref:roleAssignmentRef,requested_action_class:"ACTIVATE",presented_source_version_ref:projection.source_version_set_ref,expected_aggregate_version:aggregateVersion,intent_time:intentTime}});setActionResult(result);const refreshed=await client.read(`/tickets/${encodeURIComponent(ticketId)}`);if(refreshed.view_id!=="UX-RS-03")throw new Error("TICKET_CONSOLE_REFRESH_VIEW_MISMATCH");setProjection(refreshed);}catch(error){setFailure(error instanceof Error?error.message:"TICKET_ACTION_FAILED");}finally{setBusy(false);}}
  const day2Actions=availableActions.filter((action)=>action!=="ACTIVATE");
  return <ViewFrame viewId="UX-RS-03" title="Ticket Operational Console"><CurrentnessBanner currentness={projectionCurrentness}/>{failure?<p role="alert">{failure}</p>:null}{!projection?<p>Loading current Ticket projection.</p>:<section data-ticket-id={ticketId} data-ticket-state={state??"UNKNOWN"} data-day2-stage={day2Stage??"UNKNOWN"}>
    <p><strong>Ticket:</strong> {ticketId}</p><p><strong>Lifecycle state:</strong> {state??"Not available from current source"} — aggregate version {aggregateVersion??"unknown"}</p><p><strong>Current Responsible Holder:</strong> {holderRef??"Missing binding"}</p><p><strong>Current action authority assignment:</strong> {roleAssignmentRef??"Missing binding"}</p><p><strong>Authority result:</strong> {authorityResultRef??"Missing binding"}</p><p><strong>Gate result:</strong> {gateResultRef??"Missing binding"}</p><p><strong>Day-2 governed stage:</strong> {day2Stage??"Not bound"}</p><p><strong>Available actions:</strong> {availableActions.length>0?availableActions.join(", "):"None"}</p>{restrictionProfile?<p><strong>Restriction:</strong> {restrictionProfile}</p>:null}
    {activatePresentation.state==="ENABLED"?<button type="button" data-action-class="ACTIVATE" disabled={busy} onClick={()=>void activate()}>{busy?"Applying…":"ACTIVATE"}</button>:null}{activatePresentation.state==="DISABLED"?<p>ACTIVATE unavailable: {activatePresentation.reason}</p>:null}
    {trainerAvailable&&ticketId?<p><a data-training-control="true" href={`/trainer/tls-day2?ticket=${encodeURIComponent(ticketId)}`}>Open Day-2 Trainer Console</a></p>:null}
    {day2Actions.map((action)=><p key={action}><a data-action-class={action} href={`/tickets/${encodeURIComponent(ticketId!)}/action/${encodeURIComponent(action)}`}>{action}</a></p>)}
    {state==="ACTIVE"||state==="TERMINAL_PROCESSING"?<p><a href={`/tickets/${encodeURIComponent(ticketId!)}/evidence`}>Evidence and Verification</a> · <a href={`/tickets/${encodeURIComponent(ticketId!)}/closure`}>Terminal / Closure Readiness</a></p>:null}
    {actionResult?<p role="status" data-action-result={actionResult.result}>Action result: {actionResult.result}; durable={String(actionResult.durable)}</p>:null}<p><a href="/work">Back to Work Queue</a></p>
  </section>}</ViewFrame>;
}
