import { useEffect, useState } from "react";
import { createUiClient, type UiResult, type UiViewEnvelope } from "../api.ts";
import { ViewFrame } from "../components/ViewFrame.tsx";

const TRAINER_INTENT="APPTS.TLS.DAY2.TRAINER.TRIGGER / 1.0.0";
const RESEED_INTENT="APPTS.TLS.DAY3.TRAINER.RESEED_RUN / 1.0.0";
const SCENARIO="TLS-D2-RS-SCN-01";
interface TrainerTarget{readonly ticket_id?:unknown;readonly current_state_code?:unknown;readonly aggregate_version?:unknown;readonly trigger_available?:unknown;readonly stage?:unknown;}
function initialTicket():string{return new URLSearchParams(location.search).get("ticket")??"";}
function text(value:unknown):string|undefined{return typeof value==="string"&&value.length>0?value:undefined;}
function targets(value:unknown):readonly TrainerTarget[]{return Array.isArray(value)?value.filter((item):item is TrainerTarget=>typeof item==="object"&&item!==null):[];}
export function TrainerConsoleView(){
  const[ticketId,setTicketId]=useState(initialTicket);const[targetList,setTargetList]=useState<readonly TrainerTarget[]>([]);const[projection,setProjection]=useState<UiViewEnvelope>();const[result,setResult]=useState<UiResult>();const[failure,setFailure]=useState<string>();const[busy,setBusy]=useState(false);const[scenarioRunRef,setScenarioRunRef]=useState(()=>crypto.randomUUID());
  async function refreshTargets(preferNew=false):Promise<void>{const client=createUiClient();const value=await client.read("/trainer/targets");const found=targets(value.data["targets"]);setTargetList(found);if(preferNew){const first=found[0];const id=text(first?.ticket_id);if(id)setTicketId(id);}else if(!ticketId){const first=found.find((item)=>item.trigger_available===true)??found[0];const id=text(first?.ticket_id);if(id)setTicketId(id);}}
  useEffect(()=>{void refreshTargets().catch((error:unknown)=>setFailure(error instanceof Error?error.message:"TRAINER_TARGET_LIST_UNAVAILABLE"));},[]);
  useEffect(()=>{if(!ticketId){setProjection(undefined);return;}const client=createUiClient();void client.read(`/trainer/tickets/${encodeURIComponent(ticketId)}`).then(setProjection).catch((error:unknown)=>setFailure(error instanceof Error?error.message:"TRAINER_TARGET_UNAVAILABLE"));},[ticketId]);
  const target=projection?.data["target"];const targetRecord=target&&typeof target==="object"?target as Readonly<Record<string,unknown>>:undefined;const state=text(targetRecord?.["current_state_code"]);const stage=text(targetRecord?.["stage"]);const triggerAvailable=targetRecord?.["trigger_available"]===true;
  async function trigger():Promise<void>{if(!ticketId||!triggerAvailable)return;setBusy(true);setFailure(undefined);try{const client=createUiClient();const outcome=await client.intent({intent_contract_ref:TRAINER_INTENT,subject_ref:ticketId,correlation_id:crypto.randomUUID(),payload:{ticketId,scenarioRunRef}});setResult(outcome);const refreshed=await client.read(`/trainer/tickets/${encodeURIComponent(ticketId)}`);setProjection(refreshed);if(outcome.result==="ACK")setScenarioRunRef(crypto.randomUUID());}catch(error){setFailure(error instanceof Error?error.message:"TRAINER_TRIGGER_FAILED");}finally{setBusy(false);}}
  async function freshRun():Promise<void>{setBusy(true);setFailure(undefined);try{const runRef=crypto.randomUUID();const client=createUiClient();const outcome=await client.intent({intent_contract_ref:RESEED_INTENT,subject_ref:"TLS-D3-RS-SCN-01",correlation_id:crypto.randomUUID(),payload:{scenarioRunRef:runRef}});setResult(outcome);setScenarioRunRef(crypto.randomUUID());await refreshTargets(true);}catch(error){setFailure(error instanceof Error?error.message:"TRAINER_RESEED_FAILED");}finally{setBusy(false);}}
  return <ViewFrame viewId="TLS-D2-TRAINER" title="TLS Trainer Console">
    <section data-training-control-plane="true"><p><strong>SIMULATION / TRAINING CONTROL — no Product Role authority.</strong></p><p>This console may issue only approved controlled simulator inputs. A fresh-run request does not delete or rewrite prior Tickets; it submits a new governed Trial intake and D-01 alone determines Ticket formation. Trainer cannot verify evidence, perform Product actions, directly advance lifecycle state, or close a Ticket.</p>{failure?<p role="alert">{failure}</p>:null}<button type="button" data-trainer-reseed="fresh-governed-run" disabled={busy} onClick={()=>void freshRun()}>{busy?"Processing…":"Start fresh governed training run"}</button><label>Controlled target <select value={ticketId} onChange={(event)=>{setTicketId(event.target.value);setResult(undefined);}}><option value="">Select target</option>{targetList.map((item)=>{const id=text(item.ticket_id);return id?<option key={id} value={id}>{id} — {text(item.current_state_code)??"UNKNOWN"}</option>:null;})}</select></label><p><strong>Target Ticket:</strong> {ticketId||"Not selected"}</p><p><strong>Current state:</strong> {state??"Unknown"}</p><p><strong>Simulation stage:</strong> {stage??"Unknown"}</p><p><strong>Approved simulated source:</strong> SIM-NMS-RS-TLS-D2-01</p><p><strong>Adapter profile:</strong> SIM-RS-QER-PROFILE-V1</p><p><strong>Event:</strong> SERVICE_RESTORATION_INDICATION = AVAILABLE</p><p><strong>Ingress contract:</strong> INT-RUN-TD-01</p><p><strong>Scenario run ref:</strong> <code>{scenarioRunRef}</code></p><button type="button" data-trainer-trigger="SERVICE_RESTORATION_INDICATION" disabled={busy||!triggerAvailable} onClick={()=>void trigger()}>{busy?"Issuing controlled trigger…":"Issue simulated restoration indication"}</button>{!triggerAvailable&&ticketId?<p>Trigger withheld by the server-derived simulation target state.</p>:null}{result?<p role="status" data-trainer-result={result.result}>Processing result: {result.result}; durable={String(result.durable)}</p>:null}</section>
  </ViewFrame>;
}
