import { useEffect, useMemo, useState } from "react";
import { createUiClient, type UiResult, type UiViewEnvelope } from "../api.ts";
import { ViewFrame } from "../components/ViewFrame.tsx";

const TRAINER_INTENT="APPTS.TLS.DAY2.TRAINER.TRIGGER / 1.0.0";
const SCENARIO="TLS-D2-RS-SCN-01";
function selectedTicket():string|undefined{const value=new URLSearchParams(location.search).get("ticket");return value&&value.length>0?value:undefined;}
function text(value:unknown):string|undefined{return typeof value==="string"&&value.length>0?value:undefined;}
export function TrainerConsoleView(){
  const ticketId=useMemo(selectedTicket,[]);const[projection,setProjection]=useState<UiViewEnvelope>();const[result,setResult]=useState<UiResult>();const[failure,setFailure]=useState<string>();const[busy,setBusy]=useState(false);const[scenarioRunRef,setScenarioRunRef]=useState(()=>crypto.randomUUID());
  useEffect(()=>{if(!ticketId){setFailure("TRAINER_TARGET_TICKET_REQUIRED");return;}const client=createUiClient();void client.read(`/tickets/${encodeURIComponent(ticketId)}`).then(setProjection).catch((error:unknown)=>setFailure(error instanceof Error?error.message:"TRAINER_TARGET_UNAVAILABLE"));},[ticketId]);
  const state=text(projection?.data["current_state_code"]);const stage=text(projection?.data["day2_stage"]);
  async function trigger():Promise<void>{if(!ticketId||state!=="ACTIVE")return;setBusy(true);setFailure(undefined);try{const client=createUiClient();const outcome=await client.intent({intent_contract_ref:TRAINER_INTENT,subject_ref:ticketId,correlation_id:crypto.randomUUID(),payload:{ticketId,scenarioRunRef}});setResult(outcome);const refreshed=await client.read(`/tickets/${encodeURIComponent(ticketId)}`);setProjection(refreshed);if(outcome.result==="ACK")setScenarioRunRef(crypto.randomUUID());}catch(error){setFailure(error instanceof Error?error.message:"TRAINER_TRIGGER_FAILED");}finally{setBusy(false);}}
  return <ViewFrame viewId="TLS-D2-TRAINER" title="TLS Day-2 Trainer Console">
    <section data-training-control-plane="true"><p><strong>Simulation control plane — not AppTS business authority.</strong></p><p>This console can issue only the approved controlled source event for <code>{SCENARIO}</code>. It cannot create Tickets, verify evidence, advance lifecycle state, or close a Ticket.</p>{failure?<p role="alert">{failure}</p>:null}<p><strong>Target Ticket:</strong> {ticketId??"Not selected"}</p><p><strong>Current state:</strong> {state??"Unknown"}</p><p><strong>Current governed stage:</strong> {stage??"Unknown"}</p><p><strong>Approved simulated source:</strong> SIM-NMS-RS-TLS-D2-01</p><p><strong>Adapter profile:</strong> SIM-RS-QER-PROFILE-V1</p><p><strong>Event:</strong> SERVICE_RESTORATION_INDICATION = AVAILABLE</p><p><strong>Ingress contract:</strong> INT-RUN-TD-01</p><p><strong>Scenario run ref:</strong> <code>{scenarioRunRef}</code></p><button type="button" data-trainer-trigger="SERVICE_RESTORATION_INDICATION" disabled={busy||state!=="ACTIVE"||stage!=="AWAITING_CONTROLLED_DAY2_TRIGGER"} onClick={()=>void trigger()}>{busy?"Issuing controlled trigger…":"Issue simulated restoration indication"}</button>{state!=="ACTIVE"?<p>Trigger withheld: target Ticket must be ACTIVE.</p>:null}{stage&&stage!=="AWAITING_CONTROLLED_DAY2_TRIGGER"?<p>Trigger withheld: this Ticket already has Day-2 governed context.</p>:null}{result?<p role="status" data-trainer-result={result.result}>Processing result: {result.result}; durable={String(result.durable)}</p>:null}{ticketId?<p><a href={`/tickets/${encodeURIComponent(ticketId)}`}>Return to Ticket Console</a> · <a href={`/tickets/${encodeURIComponent(ticketId)}/evidence`}>Open Evidence and Verification</a></p>:null}</section>
  </ViewFrame>;
}
