import { useEffect, useState } from "react";
import { createUiClient, type UiViewEnvelope } from "../api.ts";
import { CurrentnessBanner, type Currentness } from "../components/CurrentnessBanner.tsx";
import { ViewFrame } from "../components/ViewFrame.tsx";

type Row=Readonly<Record<string,unknown>>;
type TicketProjection = Readonly<{ ticket_id?: unknown; current_state_code?: unknown; aggregate_version?: unknown; currentness_ref?: unknown; operational_attention?: unknown; }>;
const currentnessValues = new Set<Currentness>(["CURRENT", "STALE", "CONTRADICTORY", "MIXED_SOURCE", "MISSING_BINDING", "UNCERTAIN"]);
function currentness(value: unknown): Currentness { return typeof value === "string" && currentnessValues.has(value as Currentness) ? value as Currentness : "MISSING_BINDING"; }
function text(value: unknown): string { return typeof value === "string" && value.length > 0 ? value : "Not available from current source"; }
function record(value:unknown):Row{return typeof value==="object"&&value!==null?value as Row:{};}
function amount(value:unknown):number{return typeof value==="number"&&Number.isFinite(value)?value:0;}
export function WorkQueueView() {
  const [projection, setProjection] = useState<UiViewEnvelope>(); const [failure, setFailure] = useState<string>();
  useEffect(() => { const client = createUiClient(); void client.read("/work-queue").then((result) => { if (result.view_id !== "UX-RS-01") throw new Error("WORK_QUEUE_PROJECTION_VIEW_MISMATCH"); setProjection(result); }).catch((error: unknown) => setFailure(error instanceof Error ? error.message : "WORK_QUEUE_PROJECTION_UNAVAILABLE")); }, []);
  const rawTickets = projection?.data["tickets"]; const tickets = Array.isArray(rawTickets) ? rawTickets.filter((item): item is TicketProjection => typeof item === "object" && item !== null) : []; const projectionCurrentness = currentness(projection?.currentness_ref);
  return <ViewFrame viewId="UX-RS-01" title="Role-Scoped Work Queue"><CurrentnessBanner currentness={projectionCurrentness} />{failure ? <p role="alert">{failure}: current work-queue projection is unavailable.</p> : null}<section data-session-context="server-derived"><p><strong>Current working Role:</strong> {text(projection?.data["session_role_ref"])}</p><p><strong>Current Holder:</strong> {text(projection?.data["session_holder_ref"])}</p><details><summary>Session traceability</summary><p>Authenticated alias: {text(projection?.data["session_alias"])}</p></details></section><p>Current role-scoped work: {tickets.length} open runtime Ticket{tickets.length === 1 ? "" : "s"}.</p>{tickets.length === 0 ? <p>No open runtime Ticket is currently assigned or action-bound to this Role context.</p> : <ul>{tickets.map((ticket, index) => { const ticketId = text(ticket.ticket_id); const key = ticketId === "Not available from current source" ? String(index) : ticketId;const attention=record(ticket.operational_attention);const waiting=amount(attention["open_waiting_count"]);const blockers=amount(attention["open_blocker_count"]);const escalations=amount(attention["escalation_count"]);const next=text(attention["next_control_class_ref"]);const hasAttention=waiting>0||blockers>0||escalations>0||next!=="Not available from current source";return <li key={key}>{ticketId === "Not available from current source" ? <strong>{ticketId}</strong> : <strong><a href={`/tickets/${encodeURIComponent(ticketId)}`}>{ticketId}</a></strong>}{" — "}{text(ticket.current_state_code)}{hasAttention?<div><strong>Operational attention:</strong> {waiting} waiting · {blockers} blocker · {escalations} escalation{escalations===1?"":"s"}{next!=="Not available from current source"?<> · next governed control is available</>:null}</div>:<div>No waiting, blocker, escalation, or next-control signal is represented in the current projection.</div>}<details><summary>Technical currentness and control references</summary><p>Aggregate version: {String(ticket.aggregate_version ?? "unknown")}</p><p>Currentness: {text(ticket.currentness_ref)}</p>{next!=="Not available from current source"?<p>Next control class: {next}</p>:null}{attention["next_control_owner_ref"]?<p>Next control owner/responsibility: {text(attention["next_control_owner_ref"])}</p>:null}</details></li>; })}</ul>}<p><a href="/intake">Open pre-Ticket intake</a> · <a href="/end-shift">End Shift Check</a></p></ViewFrame>;
}
