import type { AuthorityResolutionPayload, CompoundContextMessage, ValidationResult } from "@appts-restore-service/contracts";
import type { AssignmentSnapshot } from "./assignment-snapshot.ts";
export interface AuthorityCandidate { readonly responsibilityId: string; readonly snapshot: AssignmentSnapshot; readonly scopeMatches: boolean; readonly ticketContextMatches: boolean; readonly evidenceSatisfied: boolean; readonly sodSatisfied: boolean; readonly policySatisfied: boolean; readonly actions: readonly { readonly action_class_ref: string; readonly permission_code: string }[]; }
export interface AuthorityInput { readonly resultId: string; readonly ticketId: string; readonly entityRef?: string; readonly domainId: string; readonly actorHolderRef?: string; readonly actingRoleInstanceRef?: string; readonly actingAssignmentRef?: string; readonly authorityBasisRef?: string; readonly contextRef: string; readonly currentnessRef: string; readonly effectiveFrom: string; readonly candidates: readonly AuthorityCandidate[]; }
const nonEmpty = (value: string | undefined): value is string => typeof value === "string" && value.length > 0;
export function resolveAuthority(input: AuthorityInput): AuthorityResolutionPayload {
  const completeActingContext = nonEmpty(input.entityRef) && nonEmpty(input.actorHolderRef) && nonEmpty(input.actingRoleInstanceRef) && nonEmpty(input.actingAssignmentRef) && nonEmpty(input.authorityBasisRef);
  const valid = completeActingContext ? input.candidates.filter((candidate) => candidate.snapshot.state === "CURRENT" && candidate.snapshot.entityRef === input.entityRef && candidate.snapshot.domainId === input.domainId && candidate.snapshot.holderRef === input.actorHolderRef && candidate.snapshot.roleInstanceRef === input.actingRoleInstanceRef && candidate.snapshot.assignmentRef === input.actingAssignmentRef && candidate.snapshot.authorityBasisRef === input.authorityBasisRef && candidate.scopeMatches && candidate.ticketContextMatches && candidate.evidenceSatisfied && candidate.sodSatisfied && candidate.policySatisfied) : [];
  const selected = valid.length === 1 ? valid[0] : undefined;
  return Object.freeze({ authority_result_id: input.resultId, ticket_id: input.ticketId, ...(completeActingContext ? { entity_ref: input.entityRef, actor_holder_ref: input.actorHolderRef, acting_role_instance_ref: input.actingRoleInstanceRef, acting_assignment_ref: input.actingAssignmentRef, authority_basis_ref: input.authorityBasisRef } : {}), domain_id: input.domainId, context_ref: input.contextRef, assignment_snapshot_refs: Object.freeze(input.candidates.map((item) => item.snapshot.snapshotId)), ...(selected ? { responsibility_id: selected.responsibilityId, responsible_assignment_ref: selected.snapshot.assignmentRef, authority_actions: Object.freeze([...selected.actions]), result_status_ref: "AUTHORIZED" } : { authority_actions: Object.freeze([]), result_status_ref: valid.length > 1 ? "UNRESOLVED_CONFLICT" : "NO_VALID_AUTHORITY" }), currentness_ref: input.currentnessRef, effective_from: input.effectiveFrom });
}
export function consumeD02CompoundContext(message: CompoundContextMessage, validation: ValidationResult): Readonly<Record<string, unknown>> {
  if (!validation.ok || message.payload.access_set_identity !== "I04-ACCESS-D02-1.0.0") throw new Error("INVALID_I04_D02_PAIRING");
  return Object.freeze({ ...message.payload.access_set_payload });
}
