import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import type { PersistencePool } from "@appts-restore-service/persistence";
import type { TlsDay3TrialAuth } from "../trial/tls-day3-auth.ts";

const UI_PREFIX="/api/v1/ui/trainer";
const D2_SOURCE_SYSTEM="52010000-0000-4000-8000-000000000003";
interface TargetRow{readonly ticket_id:string;readonly current_state_code:string;readonly aggregate_version:string;readonly evidence_present:boolean;}
function routeParam(request:FastifyRequest,name:string):string|undefined{const params=request.params;if(typeof params!=="object"||params===null)return undefined;const value=(params as Readonly<Record<string,unknown>>)[name];return typeof value==="string"&&value.length>0?value:undefined;}
function failure(reply:FastifyReply,error:unknown):FastifyReply{const code=error instanceof Error?error.message:"TLS_DAY3_TRAINER_TARGET_ERROR";return reply.code(code==="TLS_DAY3_AUTHENTICATION_REQUIRED"?401:403).header("Cache-Control","no-store").send({error:code});}
function envelope(rows:readonly TargetRow[],subjectRef?:string):Readonly<Record<string,unknown>>{const targets=rows.map((row)=>Object.freeze({ticket_id:row.ticket_id,current_state_code:row.current_state_code,aggregate_version:Number(row.aggregate_version),trigger_available:row.current_state_code==="ACTIVE"&&!row.evidence_present,stage:row.current_state_code!=="ACTIVE"?row.current_state_code:row.evidence_present?"DAY2_GOVERNED_CONTEXT_EXISTS":"AWAITING_CONTROLLED_DAY2_TRIGGER"}));return Object.freeze({view_id:subjectRef?"TLS-D2-TRAINER-TARGET":"TLS-D2-TRAINER-TARGETS",...(subjectRef?{subject_ref:subjectRef}:{}),source_version_set_ref:`trainer-targets:${targets.length}:${targets.reduce((max,item)=>Math.max(max,item.aggregate_version),0)}`,generated_at:new Date().toISOString(),currentness_ref:"CURRENT",data:Object.freeze({simulation_control_plane:true,product_authority:false,target_count:targets.length,targets:Object.freeze(targets),...(subjectRef?{target:targets[0]??null}:{})})});}
async function rows(pool:PersistencePool,ticketId?:string):Promise<readonly TargetRow[]>{const parameters:readonly unknown[]=ticketId?[D2_SOURCE_SYSTEM,ticketId]:[D2_SOURCE_SYSTEM];const where=ticketId?"WHERE rt.ticket_id=$2":"WHERE rt.current_state_code<>'CLOSED'";const result=await pool.query<TargetRow>(`SELECT rt.ticket_id::text,rt.current_state_code,rt.aggregate_version::text,EXISTS(SELECT 1 FROM appts.qualified_external_record q WHERE q.ticket_id=rt.ticket_id AND q.source_system_ref_id=$1) AS evidence_present FROM appts.runtime_ticket rt ${where} ORDER BY rt.updated_at DESC,rt.ticket_id LIMIT 100`,[...parameters]);return result.rows;}
export function registerTlsDay3TrainerRoutes(app:FastifyInstance,pool:PersistencePool,auth:TlsDay3TrialAuth):void{
  app.get(`${UI_PREFIX}/targets`,async(request,reply)=>{try{auth.requireTrainer(request);return reply.header("Cache-Control","no-store").send(envelope(await rows(pool)));}catch(error){return failure(reply,error);}});
  app.get(`${UI_PREFIX}/tickets/:ticketId`,async(request,reply)=>{try{auth.requireTrainer(request);const ticketId=routeParam(request,"ticketId");if(!ticketId)throw new Error("TLS_DAY3_TRAINER_TARGET_REQUIRED");const result=await rows(pool,ticketId);if(result.length!==1)throw new Error("TLS_DAY3_TRAINER_TARGET_NOT_FOUND");return reply.header("Cache-Control","no-store").send(envelope(result,ticketId));}catch(error){return failure(reply,error);}});
}
