import type { CompoundContextMessage, EvidenceGateResultPayload, ValidationResult } from "@appts-restore-service/contracts";
import type { VerificationResult } from "./verification.ts";
export type GatePredicateStatus = "SATISFIED" | "FAILED" | "MISSING" | "STALE" | "CONTRADICTED";
export interface GatePredicate { readonly identity: string; readonly status: GatePredicateStatus; readonly inputRecordRef?: string; readonly reasonRef?: string; }
export interface GateInput { readonly gateResultId: string; readonly ticketId: string; readonly entityRef?: string; readonly gateIdentity: string; readonly evaluationId: string; readonly actorHolderRef?: string; readonly actingRoleInstanceRef?: string; readonly actingAssignmentRef?: string; readonly authorityBasisRef?: string; readonly inputVersionSetRef: string; readonly currentnessRef: string; readonly effectiveFrom: string; readonly predicates: readonly GatePredicate[]; readonly verification?: VerificationResult; readonly requestedProgressionClasses: readonly string[]; }
const nonEmpty = (value: string | undefined): value is string => typeof value === "string" && value.length > 0;
export function evaluateGate(input: GateInput): EvidenceGateResultPayload {
  const completeActingContext = nonEmpty(input.entityRef) && nonEmpty(input.actorHolderRef) && nonEmpty(input.actingRoleInstanceRef) && nonEmpty(input.actingAssignmentRef) && nonEmpty(input.authorityBasisRef);
  const satisfied = completeActingContext && input.predicates.length > 0 && input.predicates.every((predicate) => predicate.status === "SATISFIED") && input.verification?.status === "VERIFIED";
  return Object.freeze({ gate_result_id: input.gateResultId, ticket_id: input.ticketId, ...(completeActingContext ? { entity_ref: input.entityRef, actor_holder_ref: input.actorHolderRef, acting_role_instance_ref: input.actingRoleInstanceRef, acting_assignment_ref: input.actingAssignmentRef, authority_basis_ref: input.authorityBasisRef } : {}), gate_identity: input.gateIdentity, gate_evaluation_id: input.evaluationId, input_version_set_ref: input.inputVersionSetRef, ...(input.verification ? { verification_result_ref: input.verification.resultRef } : {}), gate_predicate_results: Object.freeze(input.predicates.map((predicate) => Object.freeze({ predicate_identity: predicate.identity, result_code: predicate.status, ...(predicate.reasonRef ? { reason_ref: predicate.reasonRef } : {}), ...(predicate.inputRecordRef ? { input_record_ref: predicate.inputRecordRef } : {}) }))), ...(satisfied ? { progression_envelope_id: `${input.evaluationId}:progression` } : {}), permitted_progression_classes: Object.freeze(satisfied ? [...new Set(input.requestedProgressionClasses)].sort() : []), currentness_ref: input.currentnessRef, effective_from: input.effectiveFrom });
}
export function consumeD03CompoundContext(message: CompoundContextMessage, validation: ValidationResult): Readonly<Record<string, unknown>> {
  if (!validation.ok || message.payload.access_set_identity !== "I04-ACCESS-D03-1.0.0") throw new Error("INVALID_I04_D03_PAIRING");
  return Object.freeze({ ...message.payload.access_set_payload });
}
