import { assertExactKeys, isRecord, issue, optionalNonEmptyString, requireNonEmptyString, requireNonNegativeInteger, requireTimestamp, resultFromIssues, type ContractId, type ContractReference, type ContractTime, type ValidationIssue, type ValidationResult } from "../common/envelope.ts";
export const INT_RUN_TD_05_IDENTITY = "INT-RUN-TD-05" as const;
export const INT_RUN_TD_05_DIRECTION = "D-06_TO_D-04" as const;
export interface ActionIntentPayload { readonly action_intent_id: ContractId; readonly ticket_id: ContractId; readonly actor_ref: ContractReference; readonly role_assignment_ref: ContractReference; readonly requested_action_class: string; readonly presented_source_version_ref: ContractReference; readonly expected_aggregate_version: number; readonly intent_time: ContractTime; }
export interface AcknowledgmentPayload { readonly acknowledgment_id: ContractId; readonly ticket_id: ContractId; readonly subject_type: string; readonly subject_id: ContractId; readonly acknowledged_by_ref: ContractReference; readonly acknowledged_at: ContractTime; readonly result_ref: ContractReference; readonly evidence_ref?: ContractReference; }
const INTENT_KEYS = new Set(["action_intent_id", "ticket_id", "actor_ref", "role_assignment_ref", "requested_action_class", "presented_source_version_ref", "expected_aggregate_version", "intent_time"]);
const ACK_KEYS = new Set(["acknowledgment_id", "ticket_id", "subject_type", "subject_id", "acknowledged_by_ref", "acknowledged_at", "result_ref", "evidence_ref"]);
export function validateActionIntent(input: unknown): ValidationResult { const issues: ValidationIssue[] = []; if (!isRecord(input)) return { ok: false, issues: [issue("$", "REQUIRED_STRUCT")] }; assertExactKeys(input, INTENT_KEYS, issues); for (const k of ["action_intent_id", "ticket_id", "actor_ref", "role_assignment_ref", "requested_action_class", "presented_source_version_ref"]) requireNonEmptyString(input, k, issues); requireNonNegativeInteger(input, "expected_aggregate_version", issues); requireTimestamp(input, "intent_time", issues); return resultFromIssues(issues); }
export function validateAcknowledgment(input: unknown): ValidationResult { const issues: ValidationIssue[] = []; if (!isRecord(input)) return { ok: false, issues: [issue("$", "REQUIRED_STRUCT")] }; assertExactKeys(input, ACK_KEYS, issues); for (const k of ["acknowledgment_id", "ticket_id", "subject_type", "subject_id", "acknowledged_by_ref", "result_ref"]) requireNonEmptyString(input, k, issues); requireTimestamp(input, "acknowledged_at", issues); optionalNonEmptyString(input, "evidence_ref", issues); return resultFromIssues(issues); }
